[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/politica-privacidad"
  to   = "/politica-privacidad.html"
  status = 200

[[redirects]]
  from = "/condiciones"
  to   = "/condiciones.html"
  status = 200

[[redirects]]
  from = "/aviso-legal"
  to   = "/aviso-legal.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
